### ISSUE TITLE
Unable to use git repos in Gemfile

### ISSUE THREAD

**Issue by tombeynon** [litaio/docker-lita#2]
First off I'll admit I'm totally new to Docker, though I do have a good background in server admin. Lita has been a great way for me to learn, but I don't seem to be able to find a way around this.. I might just be missing something simple. 

I've tried to use a git repo as the source for a gem, but since the docker container doesn't have git installed, bundler naturally fails. 

```
gem "lita-against-humanity", :github => 'muyjohno/lita-against-humanity'
```

Is there any way to install git in the container before bundler is run, without manually recreating the docker file and making my changes? Would it be worth including git in your Dockerfile to cover this eventuality, and also issues like https://github.com/litaio/docker-lita/issues/1?

**Comment by jimmycuadra** [comment]
Since not everyone has Git gems as dependencies, I'd rather not include Git in the image itself. However, it's easy to create an image of your own that uses this one as a base. You'd just need a Dockerfile that looks like this:

``` Dockerfile
FROM litaio/lita

RUN apt-get update && apt-get -y install git && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
```

You can build this with the shell command `docker build -t yourname/lita-with-git .` (obviously replacing the user and image names with whatever you like.

**Comment by tombeynon** [comment]
I didn't realise it was that easy - exactly what I needed. Thanks very much for your help.
